---
title: "GOeval"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GOeval}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Steps to use this package from original network to graphing the results:
1. subset_network to create network subsets with the top-weighted edges
2. webgestalt_network on each of the network subsets to generate ORA results
3. get_metrics on the stored ORA results to calculate summary statistics for plotting
4. plot_metrics using the output of get_metrics

```{r setup}
library(ontologyIndex)
library(WebGestaltR)
library(GOeval)
#devtools::load_all()
```

```{r}
# 1. subset_network
# subset_network()

# 2. webgestalt_network
webgestalt_network(file.path("data", "small_net.tsv"), file.path("data", "small_net_gene_universe.txt"), file.path("data", "small_net_output"), "small_net_194", permutations = 2)
```

```{r}
  output_folders <- c(file.path("data", "np3_example"), file.path("data", "marbach_example"))

  title_text = "NP3 vs Marbach et al."
  subtitle_text = "subset for overlapping TFs"

  # load regulatory relationships between GO terms for the calculation of
  #   overlap between TF GO annotations and their targets' enriched GO terms
  go <- as.data.frame(get_ontology(file = "http://purl.obolibrary.org/obo/go/go-basic.obo", extract_tags = "everything"))
  go <- go[go$namespace == 'biological_process',]
  go_reg <- go[c('id', 'regulates', 'negatively_regulates', 'positively_regulates')]
  rm(go)

  # load gene annotations with WebGestaltR::loadGeneSet
  suppressWarnings(go_ann <- loadGeneSet(organism = "hsapiens", enrichDatabase = "geneontology_Biological_Process_noRedundant", hostName = "https://www.webgestalt.org/")$geneSet)

  # 3. get_metrics
  metric_dfs_by_net <- mapply(get_metrics, output_folders, MoreArgs=list(get_percent = TRUE, get_mean = TRUE, get_median = TRUE, get_annotation_overlap = TRUE, go_ann = go_ann, go_reg = go_reg, parallel = FALSE), SIMPLIFY = FALSE)

  #pdf(file.path("data", "npVm_example.pdf"), 7, 5)

  # 4. plot_metrics
  plot_metrics(metric_dfs_by_net, title_text, subtitle_text)

  #dev.off()
```
